Fix `puppet generate types`
When running puppet generate types, the following error is raised:

Notice: Generating Puppet resource types.
Error: Failed to load custom type 'grafana_ldap_config' from '/etc/puppetlabs/code/environments/production/modules/grafana/lib/puppet/type/grafana_ldap_config.rb': uninitialized constant Puppet::Parameter::Boolean

Adding this require statement fix this issue.